### ISSUE TITLE
fix ubuntu dev to remove warnings

### ISSUE THREAD

**Issue by lwhittles** [mrc-ide/gonovax#123]
Can this be solved by recompiling odin? Ask @richfitz when back from holiday

<img width="1020" alt="Screenshot 2024-03-15 at 15 11 53" src="https://github.com/mrc-ide/gonovax/assets/12626690/ef4ca355-1e00-44fa-8fc5-779e303c32bd">

**Comment by richfitz** [comment]
Yes, the fix for this is in the latest odin, please let me know if you've does not fix it
